apiVersion: v1
kind: Template
labels:
  template: user-engagement-api
metadata:
  name: user-engagement-api
  annotations:
    description: user-engagement-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: user-engagement-api
    name: user-engagement-api
  spec:
    selector:
      service: user-engagement-api
    template:
      metadata:
        labels:
          service: user-engagement-api
      spec:
        containers:
        - env:
          - name: BAYESIAN_COMPONENT_TAGGED_COUNT
            value: "2"
          - name: COMPONENT_ANALYSES_LIMIT
            value: ${COMPONENT_ANALYSES_LIMIT}
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: WORKER_ADMINISTRATION_REGION
            value: "api"
          - name: F8_API_BACKBONE_HOST
            value: "http://f8a-server-backbone:5000"
          - name: OSIO_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: auth-url
          - name: BAYESIAN_FETCH_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: auth-url
          - name: FABRIC8_ANALYTICS_JWT_AUDIENCE
            value: "fabric8-online-platform,openshiftio-public,https://prod-preview.openshift.io,https://openshift.io"
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: worker
                key: sentry_dsn
          - name: THREESCALE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: 3scale
                key: three_scale_account_secret
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: user-engagement-api
          ports:
          - containerPort: 9000
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: 9000
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: user-engagement-api
    name: user-engagement-api
  spec:
    ports:
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      service: user-engagement-api
- apiVersion: v1
  kind: Route
  metadata:
    name: user-engagement-api
  spec:
    host: ${USER_ENGAGEMENT_API_HOSTNAME}
    to:
      kind: Service
      name: user-engagement-api

parameters:
- description: API end points to publish user engagement metrics
  displayName: Publish User engagement metrics API 
  required: false
  name: USER_ENGAGEMENT_API_HOSTNAME

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "docker.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "meerakrishna/engagement-metrics"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "1.0"  # image-tag

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "2"

- description: Number of dependencies allowed in one component analyses call
  displayName: Number of dependencies allowed in one component analyses call
  required: true
  name: COMPONENT_ANALYSES_LIMIT
  value: "10"

- description: "Flask logging level (see: https://docs.python.org/3/library/logging.html#levels)"
  displayName: Flask logging level
  required: false
  name: FLASK_LOGGING_LEVEL
  value: "WARNING"
